# Generated by Django 4.2.3 on 2023-07-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_crawler_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
