# Generated by Django 4.2.3 on 2023-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('keyword', models.CharField(max_length=100)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
    ]
